### PR TITLE
add Task 11

### PR DESCRIPTION
**Pull request by val-fom**
demo: https://val-fom.github.io/assignments_val-fom/task_11/index.html

### CODE REVIEW

**Comment by xandzia** [comment]
screenshot from 2018-01-26 18-25-12
it's on a big screen. One thing you could add to  "form" is "flex-direction: column".

**Comment by val-fom** [comment]
@xandzia , thx) fixed it

**Review by AleshaOleg — APPROVED** [review]
lgtm

**Review by turchak — APPROVED** [review]
Nice work!

**Pull request merged**
